// Code generated by MockGen. DO NOT EDIT.
// Source: E:\coding\GO\Multi-person chat 2.0\backend\store\user_store.go
//
// Generated by this command:
//
//	mockgen -source=E:\coding\GO\Multi-person chat 2.0\backend\store\user_store.go -destination=E:\coding\GO\Multi-person chat 2.0\backend\store/mocks/mock_user_store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "go-chat/backend/models"
	reflect "reflect"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gomock "go.uber.org/mock/gomock"
)

// MockUserStorer is a mock of UserStorer interface.
type MockUserStorer struct {
	ctrl     *gomock.Controller
	recorder *MockUserStorerMockRecorder
	isgomock struct{}
}

// MockUserStorerMockRecorder is the mock recorder for MockUserStorer.
type MockUserStorerMockRecorder struct {
	mock *MockUserStorer
}

// NewMockUserStorer creates a new mock instance.
func NewMockUserStorer(ctrl *gomock.Controller) *MockUserStorer {
	mock := &MockUserStorer{ctrl: ctrl}
	mock.recorder = &MockUserStorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStorer) EXPECT() *MockUserStorerMockRecorder {
	return m.recorder
}

// CheckUserExists mocks base method.
func (m *MockUserStorer) CheckUserExists(ctx context.Context, email, username string) (bool, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserExists", ctx, email, username)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckUserExists indicates an expected call of CheckUserExists.
func (mr *MockUserStorerMockRecorder) CheckUserExists(ctx, email, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserExists", reflect.TypeOf((*MockUserStorer)(nil).CheckUserExists), ctx, email, username)
}

// CreateUser mocks base method.
func (m *MockUserStorer) CreateUser(ctx context.Context, user models.User) (primitive.ObjectID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(primitive.ObjectID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserStorerMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserStorer)(nil).CreateUser), ctx, user)
}

// FindUserByEmail mocks base method.
func (m *MockUserStorer) FindUserByEmail(ctx context.Context, email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByEmail", ctx, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByEmail indicates an expected call of FindUserByEmail.
func (mr *MockUserStorerMockRecorder) FindUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByEmail", reflect.TypeOf((*MockUserStorer)(nil).FindUserByEmail), ctx, email)
}

// FindUserByGoogleID mocks base method.
func (m *MockUserStorer) FindUserByGoogleID(ctx context.Context, googleID string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByGoogleID", ctx, googleID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByGoogleID indicates an expected call of FindUserByGoogleID.
func (mr *MockUserStorerMockRecorder) FindUserByGoogleID(ctx, googleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByGoogleID", reflect.TypeOf((*MockUserStorer)(nil).FindUserByGoogleID), ctx, googleID)
}
